### ISSUE TITLE
Peer Certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-site-angular#10]
Webhook fails to call hetzner's openshift machine and reports

Peer Certificate cannot be authenticated with given CA certificates

![screenshot 2018-05-18 19 32 57](https://user-images.githubusercontent.com/463790/40249153-611d7efa-5ad2-11e8-91f8-d544a45e8db4.png)

**Comment by cmoulliard** [comment]
We can avoid this error if we disable the SSL verification.

**Comment by cmoulliard** [comment]
Now, we are getting an error 401

![screenshot 2018-05-18 19 39 43](https://user-images.githubusercontent.com/463790/40249457-5a65dec6-5ad3-11e8-8ce8-e6e6efd3c1c6.png)

**Comment by cmoulliard** [comment]
HTTP Error 404 is due to secret using too special chars

**Comment by lincolnthree** [comment]
@cmoulliard This issue can be closed, yes?
