### ISSUE TITLE
Auto deploy external route for Launcher Backend

### ISSUE THREAD

**Issue by lincolnthree** [snowdrop/snowdrop-site-angular#13]
We need to be able to access the launcher backend from the custom frontend, e.g. the client web browser.

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2018-05-22T14:33:30Z'
  labels:
    app: fabric8-launcher
    service: launcher-backend
    template: launcher-header
  name: backend-public
  namespace: devex
  resourceVersion: '1414306'
  selfLink: /apis/route.openshift.io/v1/namespaces/devex/routes/backend-public
  uid: 192b26f5-5dcd-11e8-a2dc-107b44b03540
spec:
  host: backend-public-devex.195.201.87.126.nip.io
  port:
    targetPort: '8080'
  to:
    kind: Service
    name: launcher-backend
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2018-05-22T14:33:30Z'
          status: 'True'
          type: Admitted
      host: backend-public-devex.195.201.87.126.nip.io
      routerName: router
      wildcardPolicy: None

```

**Comment by lincolnthree** [comment]
@geoand Tagging you since I think this needs to go in the deployment script. (Or we can do it manually and not delete the namespace, which is what I've done for now.) If there's another way to do this or if it's not needed, then I'm all ears!

**Comment by geoand** [comment]
I can't really say I can be done any other way since I don't really know what you trying to achieve.
I haven't really been following up on the development / deployment process of the website

**Comment by cmoulliard** [comment]
Any service deployed on openshift or k8s can access another using this convention - https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ @lincolnthree

**Comment by lincolnthree** [comment]
@cmoulliard That would be fine, except this isn't accessed within the k8s instance. It's a public http request that comes from the client's web browser.

**Comment by lincolnthree** [comment]
@cmoulliard Maybe it's not required.

**Comment by lincolnthree** [comment]
This is not required. The launcher frontend exposes a route to the backend via:

`/launch/api`

This route is not required.
