### ISSUE TITLE
Use same buttons for the guides

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-site-angular#16]
We should use the same buttons no matter if the guide is a booster/project/quickstart 

- `Download` : button link to generate a project OR to download from github the src zipped project
- `Guide` : button link of the guide, README.adoc file, ....

Remark : That should be better to have an upstream guide managed by snowdrop instead of what is published as the content developed under the [web site](https://appdev.openshift.io/docs/spring-boot-runtime.html) is RHOAR focused, describe different deployment approaches which aren't the one that we will promote under snowdrop

**Comment by lincolnthree** [comment]
Moved to JIRA: https://issues.jboss.org/browse/SB-687
