### ISSUE TITLE
Can we group the guides / domain ?

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-site-angular#17]
Currently, the `/guides` page displays all the guides in a random fashion mode. It could interesting to group them per domain or topic

E.g

Microservices
Health Check guide | Circuit Breaker guide

Cloud features
Distributed Tracing guide | Config Map guide ...

Enterprise
REST guide | CRUD guide | WAR packaging guide | SSO and Security
Caching guide

ServiceMesh
Istio - guide1 | Istio - guide 2 | Istio - guide3 

Integrate
Camel - route 

Remark : domain names such as servicemesh, enterprise, microservices should be discussed with the name to find a consensus about the name

**Comment by lincolnthree** [comment]
Done! I think this looks really good. We'll need to review the categories/topics.
