### ISSUE TITLE
[Suggestion] - Guide's improvements

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-site-angular#23]
- [x]  Can we enrich the section `Keep Learning` or maybe under another name's section `Technology`  to add technology related projects suc as by example for caching -> infinispan ?
- [x] Can we also add the spring boot starters + link which have been used to create the code of a guide (that could bring added value for the user if he/she would like to create its own project) - see spring project : https://spring.io/guides/gs/rest-service/? 
- [x] We should perhaps add a link as snippet code to show such starters used ?
- [x] We can download the project from the "guides" page but not within the guide page ?
- [x] Can you also add as `topic` the name the upstream project within the `guides`'s search page. E.g. : For caching -> topic : caching, infinispan; For security -> topic: sso, keycloak, security, ...
https://www.dropbox.com/s/vc4l8o8cmw4fe11/Screenshot%202018-06-28%2008.29.53.png?dl=0

**Comment by cmoulliard** [comment]
@lincolnthree : Added a new point to the list

**Comment by cmoulliard** [comment]
Some examples illustrating lack of uniformity between Guides's name and topics definition (to support last point of my list)

1) Upstream project - title
![screenshot 2018-07-02 14 30 18](https://user-images.githubusercontent.com/463790/42163950-c220d09e-7e04-11e8-9e7c-3a1f2225a2df.png)

istio is the upstream code name of the project - `An open platform to connect, manage, and secure microservices` but doesn't correspond to the architecture's design pattern it resolves which is a [`servicemesh`](https://blog.buoyant.io/2017/04/25/whats-a-service-mesh-and-why-do-i-need-one/). 

In this case, the title should be `Servicemesh - Circuit Breaker` and topics `circuit breaker`, `servicemesh`, `istio`

2) Upstream project not defined as topic
![screenshot 2018-07-02 14 30 24](https://user-images.githubusercontent.com/463790/42163951-c246b714-7e04-11e8-9c60-d17cff219c65.png)

The title name is correct as it uses as word, the pattern `opentracing` but topics doesn't include the name of the upstream project `jaeger`

3) Core upstream project not defined as topic
![screenshot 2018-07-02 14 30 36](https://user-images.githubusercontent.com/463790/42163953-c2680df6-7e04-11e8-9402-9ff73eaeb38f.png)

We include, part of the tile name, the upstream project but we are missing the major pattern implemented by this project which is `Data full text-search`

Title should be `Full text data Search ...`
Topic : `hibernate-search`, ...

**Comment by lincolnthree** [comment]
Done!
