### ISSUE TITLE
Improve graphical style of the guide

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-site-angular#24]
The display of the page could be improved by 

- [x] Making title bigger or in bold 
- [x] Align guide's text with the title
- [x] Could we add expandable sections to refer by example to common sections explaining how to `Build from docker`, `Build from k8s`, `Build using OpenShift`, .... - WDYT 

![screenshot 2018-06-28 08 43 18](https://user-images.githubusercontent.com/463790/42017511-a4543676-7aaf-11e8-9546-8cf48ca8954a.png)

**Comment by lincolnthree** [comment]
![image](https://user-images.githubusercontent.com/362329/42053540-cd66ca12-7adf-11e8-84e0-22b68563390b.png)

Thoughts?

**Comment by cmoulliard** [comment]
> but are these just examples?
No. They will point to common `doc` explaining how a docker's user will build/deploy the project, ...
The idea here with such `Build` section is to tell to a docker, k8s or openshift user what they should. I propose that we stay focused for the moment on docker, openshift and that we remove k8s.

Can you rename `pre-req` to `build` as pre-req should point to doc explaining how to install docker, openshift. Maybe we need both ?

**Comment by lincolnthree** [comment]
We probably need both "Pre-req" and "Next steps" --- it would be difficult to embed things into the middle of the guide, but I can possibly look into that as well. It would make our asciidoc non-portable.

**Comment by lincolnthree** [comment]
Actually, it could be done portably maybe.
