### ISSUE TITLE
Discuss and review homepage content

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-site-angular#3]
- Microservices for Developers: Is it this problematic that we want to address within Snowdrop web site ? Is it only focused around Microservices or Services, ...

- **C**ontinuous **a**pplication **d**elivery for Spring Boot - built and deployed on OpenShift : We should review this sentence too as CAD is relevant is we use Jenkinspipeline, s2i with github event triggering build, ... 

- Rename `launch your project` button. The word `launch` is coming from the idea discussed during Obsidian F2F meeting to use space conquest as thematic for the creation of the project generating the code. Personally, I think that this name is confusing like mission, boosters. This is why I propose to rename it to `Generate your cloud project`, `Generate and Deploy your cloud native application`, .... WDYT @metacosm @lincolnthree @geoand @gytis

<img width="1071" alt="screenshot 2018-05-18 06 48 58" src="https://user-images.githubusercontent.com/463790/40216588-f2e93f06-5a67-11e8-99e9-837025a32979.png">

**Comment by gytis** [comment]
I like the launch related idioms. However, if we want to use more common word I would prefer to stick to short phrases e.g. create your project, start the project etc. We could specify more info such as that the project is cloud native in a tooltip

**Comment by geoand** [comment]
>  Did they come to Snowdrop to do exactly Spring Boot on OpenShift, or did they come to Snowdrop to get Microservices running in a cloud and they aren't sure of which cloud

Would it be possible for us to have simple analytics like referers etc (perhaps via Google Analytics)? That would potentially help answer such questions

**Comment by lincolnthree** [comment]
Completed. Further discussion to be done in a new issue.
