### ISSUE TITLE
Should we keep documentation page under site repo ?

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-site-angular#4]
Should we keep the documentation page under github site repo instead of this new angular site ?

As the new site do the asciidoctor to html rendering with asciidoctor.js, then I don't see why we should keep it separated

**Comment by lincolnthree** [comment]
No preference really. It might be easier to use GitHub since that's what a lot of projects do.

**Comment by cmoulliard** [comment]
This is perhaps easier to be maintained under github but then under this github repo then ?

**Comment by cmoulliard** [comment]
Can you move the adoc files from the old github snowdrop repo to this one please ? @lincolnthree

**Comment by lincolnthree** [comment]
Hey @cmoulliard. I am planning on moving these files to a new github repo, since it is probably not a good idea to force a rebuild of the site (via github webhook) every time we change one of the dynamically loaded files.

Of course there's no "harm", just some wasted electricity, but given that the files are not used at build time, what are your thoughts?

**Comment by cmoulliard** [comment]
+1 to keep them out of sinc with the github webhook of this project. But how do you plan them to move the content within the docker container created during node s2i build of the front ? @lincolnthree

**Comment by lincolnthree** [comment]
@cmoulliard They are not required in the docker container. They are loaded by the client browser HTTP client: https://github.com/snowdrop/snowdrop-site-angular/blob/master/src/assets/registry.json (This file configures their location, so they can be changed and users will see the updates as soon as their page is refreshed.)

**Comment by cmoulliard** [comment]
ok to keep the `registry.json` file with links to the different assets.

We should perhaps then : 
- [ ] Rename the github repo of the old web site from `site` to `snowdrop-doc`
- [ ] Clean (= remove jekyll content) of the old project to only keep the `*.adoc` files
- [ ] Use `snowdrop-doc` as web site doc project, team's doc, ....

**Comment by lincolnthree** [comment]
@cmoulliard +1 to all the above. I'll work on that today.

**Comment by lincolnthree** [comment]
Done. https://github.com/snowdrop/snowdrop-docs
