### ISSUE TITLE
Missing menu sections

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-site-angular#5]
The new we site doesn't contain sections to display `News or info, blog message with discuss section` where we can publish new BOM, new starters, new development around Service Catalog (e.g. https://spring.io/blog)

**Comment by lincolnthree** [comment]
Done. This can now be edited dynamically by changing the following file (no redeploy needed):
https://github.com/snowdrop/site/blob/master/news.adoc

The news (and docs) page target is controlled by registry.json:
https://github.com/snowdrop/snowdrop-site-angular/blob/master/src/assets/registry.json
